locale: "en-US"
site_theme: "default"
title: "Junteng Liu"
title_separator: "-"
name: "Junteng Liu"
description: "Junteng Liu's academic portfolio"
url: "https://kcute8132.github.io"
baseurl: "/LJT-Homepage"
repository: "kcute8132/LJT-Homepage"

author:
  avatar: ""
  name: "Junteng Liu"
  bio: "First-year PhD candidate at HKUST NLP Group"
  employer: "HKUST NLP Group"
  email: "jliugi@connect.ust.hk"
  googlescholar: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
  github: "Vicent0205"
  twitter: "junteng88716710"

publication_category:
  conferences:
    title: "Publications"

future: true
breadcrumbs: false
read_more: "disabled"
talkmap_link: false
comments:
  provider:
atom_feed:
  hide: false
analytics:
  provider: "false"

include:
  - _pages
  - files
exclude:
  - .github
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - package.json*
  - README.md

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true

timezone: Etc/UTC
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: false

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
whitelist:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
compress_html:
  clippings: all
  ignore:
    envs: development
